DROP TABLE IF EXISTS public.comments;
DROP TABLE IF EXISTS public.bookings;
DROP TABLE IF EXISTS public.items;
DROP TABLE IF EXISTS public.item_requests;
DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.item_requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(1024),
    owner_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_item_request PRIMARY KEY (id),
    CONSTRAINT item_requests_user_id_fkey FOREIGN KEY (owner_id)
        REFERENCES public.users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    owner_id BIGINT NOT NULL,
    item_request_id BIGINT,
    available BOOLEAN NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT items_user_id_fkey FOREIGN KEY (owner_id)
        REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT item_requests_item_id_fkey FOREIGN KEY (item_request_id)
        REFERENCES public.item_requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(2048) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT comments_user_id_fkey FOREIGN KEY (author_id)
        REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT comments_item_id_fkey FOREIGN KEY (item_id)
        REFERENCES public.items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booker_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    start_dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(128) NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT bookings_user_id_fkey FOREIGN KEY (booker_id)
        REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT bookings_item_id_fkey FOREIGN KEY (item_id)
        REFERENCES public.items (id) ON DELETE CASCADE
);